Feature/improve desktop ui
MonarchsofCoding/chitchat pull request #25
Opened 2017-03-23 20:57 UTC by spiroskous

2017-03-23 21:21 UTC, VJftw requested changes

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/BaseView.java
> +        header.setStyle("-fx-background-color:  #3C4F76;");
Move this into the stylesheet (`resources/chitchat.css`). You can do
```
#base-header {
  -fx-background-color:  #3C4F76;
}
```

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/BaseView.java
> +            logout.setStyle("-fx-background-color: transparent");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/BaseView.java
> +            logout.setId("logoutbtn");
Should follow the existing form (*view*-*name*-*control type*) to be `base-logout-btn`.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/BaseView.java
> +        footer.setStyle("-fx-background-color:  #3C4F76;");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/BaseView.java
> +        credits.setId("credits");
Should be `base-footer-credits`

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/authentication/LoginView.java
> +        this.loginBtn.setStyle("-fx-background-color: rgba(93,200,127,0.99)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/authentication/LoginView.java
> +        this.registerBtn.setStyle("-fx-background-color: rgba(129,178,248,0.99)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/authentication/LoginView.java
>          this.unexpectedErrors.setTextFill(Color.RED);
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/authentication/RegistrationView.java
> +        this.registerBtn.setStyle("-fx-background-color: rgba(93,200,127,0.99)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/authentication/RegistrationView.java
> +        this.loginBtn.setStyle("-fx-background-color: rgba(129,178,248,0.99)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/ConversationView.java
> +        header.setFont(Font.font(null, FontWeight.BOLD, 15));
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/ConversationView.java
> +        header.setTextFill(Color.BLUE);
Use the stylesheet

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/ConversationView.java
> +        this.sendbtn.setStyle("-fx-background-color: rgba(32,137,72,0.99)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/SearchView.java
> +        this.searchBtn.setStyle("-fx-background-color: rgba(56,64,166,0.87)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/SearchView.java
> +        this.startConversationBtn.setStyle("-fx-background-color: rgba(32,137,72,0.99)");
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/ConversationView.java
>          this.errormessage.setTextFill(Color.RED);
Use the stylesheet.

2017-03-23 21:21 UTC, VJftw commented on java_client/ChitChatDesktop/src/com/moc/chitchat/view/main/SearchView.java
>          this.errorMessage.setTextFill(Color.RED);
Use the stylesheet.

2017-03-24 00:07 UTC, AigerimSerikbekova approved these changes

2017-03-25 12:03 UTC, VJftw commented
Ran the android_client/e2e locally. All passing :100:

2017-03-25 12:03 UTC, VJftw approved these changes

2017-03-25 12:06 UTC, Ozhan-Azizi requested changes
can you try to make the listview bigger cause it is a line and we miss the returned user after usersearch

2017-03-25 12:54 UTC, AigerimSerikbekova approved these changes

2017-03-25 13:26 UTC, Ozhan-Azizi approved these changes

2017-03-25 13:28 UTC, merged