Final Report
MonarchsofCoding/chitchat pull request #36
Opened 2017-03-28 23:00 UTC by VJftw

I'll try to keep this PR updated with new PDFs when people push. (most recent one will be first).

If you're happy with the report, approve this PR.

27df6d6: [final-report.pdf](https://github.com/MonarchsofCoding/chitchat/files/877315/final-report.pdf)

---

- [ ] I need to check with Dr. Tratt if we have to move the `final_report` directory to the root.

2017-03-28 23:41 UTC, AigerimSerikbekova approved these changes

2017-03-29 15:29 UTC, FareedQasim approved these changes

2017-03-29 16:08 UTC, spiroskous requested changes
Exising to Existing and one more if it is ok the -> that I putted on JavaFx-JavaSwing on conflicts then keep it

2017-03-29 16:25 UTC, spiroskous approved these changes

2017-03-29 17:38 UTC, aakyol approved these changes

2017-03-29 21:18 UTC, Ozhan-Azizi approved these changes

2017-03-29 23:36 UTC, merged