Feature/user signs in
MonarchsofCoding/chitchat pull request #4
Opened 2017-02-16 16:02 UTC by aakyol

Hi all. Since we are done with sign in, VJ said we should do a PR on it, hence my request.

2017-02-16 16:05 UTC, AigerimSerikbekova approved these changes

2017-02-16 16:07 UTC, spiroskous approved these changes

2017-02-16 16:38 UTC, VJftw requested changes
@aakyol just the one android change and i'll do the others for the backend and java client as i initiated those and should have cleaned up after myself :p

2017-02-16 16:38 UTC, VJftw commented on android_client/ChitChat/app/src/main/java/com/moc/chitchat/activity/LoginActivity.java
> +        } catch (Exception e) {
@aakyol The try/catch here is redundant and so is the String.format :) So this bit could just be:
```
Toast.makeText(this,
            "Invalid credentials or you didn't registered yet",
            Toast.LENGTH_LONG
        ).show();
```

2017-02-16 16:38 UTC, VJftw commented on backend/chit_chat/config/config.exs
> +  secret_key: "cQCWxKpcuixeB4ZAxCs04nrBGdKeJiHcmmCHbZPI6esGcLcfZVz1qw2796p3gWGA",
I need to extract this into an environment variable for use in the docker containers.

2017-02-16 16:38 UTC, VJftw commented on java_client/ChitChatDesktop/test/com/moc/chitchat/application/ApplicationLoaderTest.java
> +//    @Test
Need to fix these tests

2017-02-16 16:38 UTC, VJftw commented on java_client/ChitChatDesktop/test/com/moc/chitchat/application/SplashWindowTest.java
> -package com.moc.chitchat.application;
Remove the SplashWindow and SplashWindowTest as it's not being used

2017-02-16 16:58 UTC, aakyol commented on android_client/ChitChat/app/src/main/java/com/moc/chitchat/activity/LoginActivity.java
> +        } catch (Exception e) {
Changing it from the browser now.

2017-02-16 17:03 UTC, VJftw commented on java_client/ChitChatDesktop/test/com/moc/chitchat/application/ApplicationLoaderTest.java
> +//    @Test
Fixed.

2017-02-16 17:03 UTC, VJftw commented on java_client/ChitChatDesktop/test/com/moc/chitchat/application/SplashWindowTest.java
> -package com.moc.chitchat.application;
Fixed.

2017-02-16 17:26 UTC, Ozhan-Azizi approved these changes

2017-02-16 17:28 UTC, FareedQasim approved these changes

2017-02-17 13:01 UTC, VJftw approved these changes

2017-02-17 13:02 UTC, merged