Feature/user sends message
MonarchsofCoding/chitchat pull request #6
Opened 2017-02-28 16:16 UTC by Ozhan-Azizi

2017-02-28 16:20 UTC, spiroskous approved these changes

2017-02-28 16:22 UTC, AigerimSerikbekova approved these changes

2017-02-28 16:25 UTC, FareedQasim approved these changes

2017-02-28 16:29 UTC, aakyol approved these changes

2017-03-02 00:30 UTC, VJftw requested changes
I need to run through the travis/invoke tasks again as I don't want this to deploy just yet as we're moving from ECS to Docker Swarm in the next feature and i'm considering not relying on Travis to deal with deployments for now. 

Otherwise, @Ozhan-Azizi @aakyol @AigerimKCL2017 @spiroskous @FareedQasim this all looks so much better with the Google checkstyle :grinning: :+1:

2017-03-02 00:30 UTC, VJftw commented on backend/chit_chat/test/controllers/message_controller_test.exs
> +  #   test "returns filtered list of users when request is authenticated and query param is valid", %{conn: conn} do
I need to remove all this commented code

2017-03-02 00:32 UTC, AigerimSerikbekova approved these changes

2017-03-02 12:21 UTC, VJftw approved these changes

2017-03-02 12:21 UTC, merged